"""Frozen V13 evidence and source-identifiability contracts."""
from __future__ import annotations

V13_SCHEMA = "google-pure-v13-source-faithful-sensitivity-scaling.v1"
SOURCE_LITERAL = "SOURCE_LITERAL"
SOURCE_ANCHORED = "SOURCE_ANCHORED"
SOURCE_UNSPECIFIED_PREREGISTERED = "SOURCE_UNSPECIFIED_PREREGISTERED"
SOURCE_UNSPECIFIED = "SOURCE_UNSPECIFIED"

NONFINAL = {
    "final_evidence": False,
    "paper_equivalence_claim_permitted": False,
    "hdfa_comparison_permitted": False,
    "paper_comparable": False,
    "reference_evidence_complete": False,
}

V12_FINDINGS = {
    "MISSING_OR_INCORRECT_SENSITIVITY_BOUNDARY": "STRONGLY_CAUSAL_IN_SYNTHETIC_STEP_AND_RECOVERY",
    "V12_SENSITIVITY_REPAIR": "EFFECTIVE_DEVELOPMENT_AMENDMENT",
    "V12_SENSITIVITY_REPAIR_SOURCE_EQUIVALENCE": "NOT_ESTABLISHED",
    "STEP_RESPONSE": "MAJOR_SYNTHETIC_SUCCESS_PENDING_SOURCE_COMPARABILITY",
    "RANDOMIZED_RECOVERY": "MAJOR_SYNTHETIC_SUCCESS",
    "FIGURE5B": "ACQUISITION_OR_CONVERGENCE_FAILURE",
    "FIGURE5C": "DERIVATIVE_CODE_PASS_REAL_FIT_UNIDENTIFIABLE",
    "NATURAL_DRIFT": "CENTRAL_SUPPRESSION_ESTIMATE_BUT_STATISTICALLY_UNRESOLVED",
    "POLICY_STATE_PERSISTENCE": "CODE_AUDITED_PASS_PROVENANCE_INCOMPLETE",
    "CANDIDATE_REWARD_PAIRING": "RUNTIME_PASS_PROVENANCE_INCOMPLETE",
    "DETECTOR_LOGICAL_ALIGNMENT": "UNRESOLVED_OUTSIDE_CONSTRUCTED_MAPPING",
    "PPO_UPDATE_LIFECYCLE": "SOURCE_COMPARABILITY_UNRESOLVED",
    "FINAL_GOOGLE_BASELINE": "NOT_READY",
}


def nonfinal(value: dict) -> dict:
    return {"schema_version": V13_SCHEMA, **value, **NONFINAL}
